#!/bin/sh

find ./ -name '*~' | xargs rm
find ./ -name '*.aux' | xargs rm
find ./ -name '*.bbl' | xargs rm
find ./ -name '*.blg' | xargs rm
find ./ -name '*.log' | xargs rm
find ./ -name '*.out' | xargs rm
find ./ -name '*.snm' | xargs rm
find ./ -name '*.toc' | xargs rm
find ./ -name '*.vrb' | xargs rm

